###
GET {{hostname}}/channels/sample/subscribe
Accept: text/event-stream

###
GET {{hostname}}/channels
Authorization: Bearer {{token}}
Accept: application/json

###
POST {{hostname}}/channels/sample
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Hello": "Hello"
}

###
DELETE {{hostname}}/channels/sample
Authorization: Bearer {{token}}
