name: Project Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Project Build]
    types: [completed]
    branches: [main]

jobs:

  deploy-server:
    name: "Deploy Server"
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Copy deployment configuration files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          strip_components: 1
          source: "deploy"
          target: "~/broadcast"
          timeout: 120s

      - name: Deploy latest version of server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd broadcast
            docker compose pull server
            docker compose up -d server
            docker image prune -f
